# Generated by Django 4.0.3 on 2022-03-11 20:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSignUpModel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=30)),
                ('created_on', models.DateTimeField()),
                ('last_modified_on', models.DateTimeField()),
            ],
        ),
    ]
